services:
  box_counter:
    build: .
    container_name: box_counter
    volumes:
      - ./images:/root/images
      - ./results:/root/results
      - ./dataset.py:/root/dataset.py
      - ./templates:/root/templates
      - ./template_matching.py:/root/template_matching.py
    working_dir: /root
    tty: true
    stdin_open: true
    entrypoint: >
      bash -c "
        pip install --no-cache-dir opencv-python-headless &&
        python3 ./template_matching.py &&
        cat results/result.csv
      "
